

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EasySchool.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SchoolEntities : DbContext
{
    public SchoolEntities()
        : base("name=SchoolEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Person> Persons { get; set; }

    public virtual DbSet<Room> Rooms { get; set; }

    public virtual DbSet<SchoolInfo> SchoolInfo { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<Grade> Grades { get; set; }

}

}

