
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EasySchool.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Message
{

    public int messageID { get; set; }

    public Nullable<int> senderID { get; set; }

    public Nullable<int> recipientID { get; set; }

    public Nullable<int> recipientClassID { get; set; }

    public bool forAllManagement { get; set; }

    public bool forAllTeachers { get; set; }

    public bool forAllStudents { get; set; }

    public bool forEveryone { get; set; }

    public string data { get; set; }

    public System.DateTime date { get; set; }

    public string title { get; set; }



    public virtual Class Class { get; set; }

    public virtual Person SenderPerson { get; set; }

    public virtual Person ReceiverPerson { get; set; }

}

}
